###
POST http://localhost:8080/api/v1/registration
Content-Type: application/json
{
  "firstName": "Bilaal",
  "lastName": "Ahmed",
  "email": "bilaal.ahmed@gmail.com",
  "password": "password"
}

###
DELETE http://localhost:8080/api/v1/registration/1

###
PUT http://localhost:8080/api/v1/registration/1?name=maria&email=maria@gmail.com

# Test
curl -X POST -H "Content-Type: application/json" -d \
'{
  "firstName": "Bilaal",
  "lastName": "Ahmed",
  "email": "bilaal.ahmed@gmail.com",
  "password": "password"
}' \
http://localhost:8080/api/v1/registration

curl -X DELETE http://localhost:8080/api/v1/student/1

curl -X PUT 'http://localhost:8080/api/v1/student/1?name=Maria&email=maria@gmail.com'

curl -X GET http://localhost:8080/api/v1/registration


curl -X POST -H "Content-Type: application/json" -d \
'{
  "firstName": "Bilaal",
  "lastName": "Ahmed",
  "email": "bilaal.ahmed@gmail.com",
  "password": "password"
}' \
http://localhost:8080/api/v1/registration

curl -X GET 'http://localhost:8080/api/v1/registration/confirm?token=92f5c336-4e86-40e6-80ca-02aaae3a1843'











-H "Accept: application/json"
text/html
application/json
multipart/form-data
