###
POST http://localhost:8080/api/v1/student
Content-Type: application/json

{
  "name": "Bilaal",
  "email": "bilaal.ahmed@gmail.com",
  "dob": "1995-12-17"
}

###
DELETE http://localhost:8080/api/v1/student/1

###
PUT http://localhost:8080/api/v1/student/1?name=maria&email=maria@gmail.com
Content-Type: application/json

# Test
curl -X POST -H "Content-Type: application/json" -d \
'{
  "name": "Bilaal",
  "email": "bilaal.ahme@gmail.com",
  "dob": "1995-12-17"
}' \
http://localhost:8080/api/v1/student

curl -X DELETE http://localhost:8080/api/v1/student/1

curl -X PUT -H "Content-Type: application/json" \
'http://localhost:8080/api/v1/student/1?name=Maria&email=maria@gmail.com'

curl -X PUT -d 'name=lo&email=alex@gmail.com' http://localhost:8080/api/v1/student/1

https://amigoscode.com/p/spring-data-jpa